### ISSUE TITLE
How can I receive and stream again?

### ISSUE THREAD

**Issue by Tuner32** [ScarletsFiction/SFMediaStream#16]
I want receive audio data from ScarletsAudioStreamer after filter and I want send by ScarletsMediaPresenter How can I do that?

**Comment by StefansArya** [comment]
You need to disconnect the presenter's AudioNode from the destination and connect it to your effect, and then connect your effect into presenter's destination.

`Presenter -> Effect -> Destination`

https://github.com/ScarletsFiction/SFMediaStream/blob/c6707c9d60225509b253e51d38ffb98b1313ef4a/example/group-call/browser/presenter.js#L86-L95

**Comment by Tuner32** [comment]
I think I am idiot. I just tried audiostream and used audioconnect fuction. Thank you. You help my project almost all.

**Comment by StefansArya** [comment]
It's okay, good luck!
