### ISSUE TITLE
Effect not working

### ISSUE THREAD

**Issue by Tuner32** [ScarletsFiction/SFMediaStream#17]
I just tried 
	presenterMedia.disconnect(presenterMedia.destination);
	ppDelay = ScarletsMediaEffect.pingPongDelay();

	ppDelay.mix(20);

	audioStreamer.connect(ppDelay.input);
	ppDelay.output.connect(presenterMedia.destination);
this. Am I wrong? it is not working

**Comment by StefansArya** [comment]
You're trying to connect the Effect like this:
`Streamer -> Effect -> Presenter's Destination`

It's just like you want to stream the sound from someone and then apply the effect and send it to presenter to record it again. Have you try to connect the streamer to the speaker instead to check if the streamer instance was working properly?

You can check with [this example](https://github.com/ScarletsFiction/SFMediaStream#example-1) or just change your code:
`presenterMedia.destination` with `ScarletsMedia.audioContext.destination`.

**Comment by Tuner32** [comment]
I just tried playStream() and it work well. with connect(presenterMedia.destination) but it send with orignal. why it is send with orignal? It is bug?

**Comment by StefansArya** [comment]
So the effect is working?
It's not a bug, it's expected because the original Presenter instance still connecting the microphone to it's destination.

`Presenter's microphone -> Presenter's destination`

That's why you need to disconnect the presenter itself from it's destination.
I think we have talk [about this](https://github.com/ScarletsFiction/SFMediaStream/issues/16#issuecomment-762253048) on the issue #16

**Comment by Tuner32** [comment]
https://pastebin.pl/view/5a4c7256
I just tried this code. Effect work perfect but it send with original.

**Comment by StefansArya** [comment]
Hmm, maybe the streamer's instance is also playing the original audio stream.

Can you try to disconnect it with?
`audioStreamer.disconnect(ScarletsMedia.audioContext.destination)`

If it's not working, try to refresh the browser with CTRL + F5 because maybe the browser was cached your old script.

**Comment by Tuner32** [comment]
I think it is play in client. I muted edit browser.

**Comment by Tuner32** [comment]
And I tried that code. but it have error

**Comment by Tuner32** [comment]
I fixed Thank you. I have to disconnect presenterMedia.destination when onRecordingReady
