### ISSUE TITLE
Implement Volume

### ISSUE THREAD

**Issue by roeilulavy** [ScarletsFiction/SFMediaStream#24]
Hello!
Love this repo!
How can I set a Volume slider (<input></input>) on the audioStreamer?

**Comment by StefansArya** [comment]
Hi!
Have you tried to connect the `audioStreamer` to [GainNode](https://developer.mozilla.org/en-US/docs/Web/API/GainNode#example)?

The implementation is similar like adding effect that created from `ScarletsMediaEffect`:
https://github.com/ScarletsFiction/SFMediaStream/blob/845df06a635f41e2ba8656967ea79b71ffcffe54/example/group-call/browser/streamer.js#L79-L83

You can get the AudioContext with `ScarletsMedia.audioContext`.

If the AudioNode is created from `audioContext` you don't need to add `.input` or `.output` properties when connecting each node, and it's should be looks like below:
```js
let gainNode = ScarletsMedia.audioContext.createGain();

// source (stream) -> GainNode -> destination (speaker) 
audioStreamer.connect(gainNode);
gainNode.connect(ScarletsMedia.audioContext.destination);

gainNode.gain.value = 0.2; // range 0~1, where 0.2 == 10%
```

**Comment by roeilulavy** [comment]
Thank you!
Works perfect!

**Comment by roeilulavy** [comment]
Now lets say I want to control the Equalizer parameters...
How do I do that?

**Comment by StefansArya** [comment]
To control the equalizer parameters, you can just adjust the frequency's dB value
https://github.com/ScarletsFiction/SFMediaStream/blob/845df06a635f41e2ba8656967ea79b71ffcffe54/src/Plugin/Equalizer.js#L35-L38

And don't forget to connect each node, different connection order may give different result

```js
let equalizer = ScarletsMediaEffect.equalizer(/* [32, 64, 125, 250, 500, 1000, 2000, 4000, 8000, 16000] */);
// 32Hz ~16KHz will be set as default frequency which you can control

// source (stream) -> Equalizer -> GainNode -> destination (speaker) 
audioStreamer.connect(equalizer.input);
equalizer.output.connect(gainNode);
gainNode.connect(ScarletsMedia.audioContext.destination);

equalizer.frequency(32, 15); // 32Hz, 15dB
```

**Comment by roeilulavy** [comment]
Thank you very much!!
